name = "Havoc Realms S5"
author = "minecraftbossdj"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "841c2e0e01011c2a37754b78f978c3549380ed46338e7b460aef6a5e75541f43"

[versions]
forge = "47.4.4"
minecraft = "1.20.1"
