name = "Havoc Realms S5"
author = "minecraftbossdj"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2a376ead4e73e0565d49fe3ef450c5a9afb2bbb1565d5aa46696a8832122244c"

[versions]
forge = "47.4.4"
minecraft = "1.20.1"
